spring.application.name=backend
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/studypulse}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=${JWT_SECRET:83f982136975a596041a84f55562719c8f2206bf2dcbc0f719b0aa90c88bc625}
app.jwt.expiration=86400000

# AI Configuration
app.ai.api-key=${AI_API_KEY:}

